package com.androhub.networkmodule.utils.imageSlider;

public enum SliderAnimations {
    ANTICLOCKSPINTRANSFORMATION,
    CLOCK_SPINTRANSFORMATION,
    CUBEINDEPTHTRANSFORMATION,
    CUBEINROTATIONTRANSFORMATION,
    CUBEINSCALINGTRANSFORMATION,
    CUBEOUTDEPTHTRANSFORMATION,
    CUBEOUTROTATIONTRANSFORMATION,
    CUBEOUTSCALINGTRANSFORMATION,
    DEPTHTRANSFORMATION,
    FADETRANSFORMATION,
    FANTRANSFORMATION,
    FIDGETSPINTRANSFORMATION,
    GATETRANSFORMATION,
    HINGETRANSFORMATION,
    HORIZONTALFLIPTRANSFORMATION,
    POPTRANSFORMATION,
    SIMPLETRANSFORMATION,
    SPINNERTRANSFORMATION,
    TOSSTRANSFORMATION,
    VERTICALFLIPTRANSFORMATION,
    VERTICALSHUTTRANSFORMATION,
    ZOOMOUTTRANSFORMATION
}
